kshrc: add gq command for quick cloning

diff --git a/etc/ksh/kshrc b/etc/ksh/kshrc
--- a/etc/ksh/kshrc
+++ b/etc/ksh/kshrc
@@ -260,6 +260,99 @@ gg() {
 }
 
 
+# gq - quickly clone or jump to repo
+
+gq() {
+    typeset repo
+    typeset repo_c
+    typeset repodir
+    typeset repotype
+    typeset codedirs
+
+    repo=$1
+
+    if [ -z "$repo" ]; then
+        printf >&2 "Usage: gq REPO\\n"
+        return 2
+    fi
+
+    if command -v git >/dev/null; then
+        for s in $(git config --get-all ghq.root); do
+            s=$(eval -- builtin cd "$s" 2>/dev/null || exit 1; pwd -P)
+            if [[ -n "$s" ]]; then
+                codedirs[${#codedirs[*]}]="${s}"
+            fi
+        done
+    fi
+
+    if [[ "${#codedirs[*]}" -lt 1 ]]; then
+        codedirs[0]=$HOME/src
+    fi
+
+    case "$repo" in
+        *.git ) repotype=git;;
+        *.hg ) repotype=git;;
+        *hg.sr.ht* ) repotype=hg;;
+        *bitbucket.com* ) repotype=hg;;
+        *bitbucket.org* ) repotype=hg;;
+        * ) repotype=git;;
+    esac
+
+    if [[ "$repo" != *"://"* && "$repo" != *"@"* ]]; then
+        repo=https://$repo
+    fi
+
+    repo_c=$(echo "$repo" |
+                   sed '
+                       s|~||;
+                       s|^.*://||;
+                       s|^\w*@||;
+                       s|.hg$||;
+                       s|.git$||')
+
+    for s in "${codedirs[@]}"; do
+        if [ -d "$s/$repo_c" ]; then
+            builtin cd "$s/$repo_c" || return 1
+            return 0
+        fi
+    done
+
+    repodir=${codedirs[0]}/$repo_c
+
+    (
+        typeset st
+        typeset basedir
+        typeset basedir_p
+
+        st=0
+        basedir=$(dirname "$repodir")
+
+        mkdir -p "$basedir"
+        cd "$basedir" || exit 1
+
+        case "$repotype" in
+            git ) git clone "$repo" || st=1;;
+            hg ) hg clone "$repo" || st=1;;
+        esac
+
+        # Cleanup in case cloning failed; we cannot use trap here
+        # since git/hg may return non-standard exit codes.
+        if [[ "$st" == "1" ]]; then
+            basedir=$repodir
+            while [[ "$basedir" != "${codedirs[0]}" ]]; do
+                rmdir "$basedir" 2>/dev/null || true
+                basedir_p=${basedir##*/}
+                basedir=${basedir%%/$basedir_p}
+            done
+        fi
+
+        return $st
+    ) || return 1
+
+    builtin cd "$repodir" || return 1
+}
+
+
 # cd - with interactive menu
 
 cd() {
